============================= test session starts ==============================
platform darwin -- Python 3.8.3, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /Users/meganfrenkel/Workspace/KERMit/server/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/meganfrenkel/Workspace/KERMit
plugins: mock-3.3.1
collecting ... collected 132 items

server/tests/integration/test_authentication.py::test_registration_missing_header ERROR [  0%]
server/tests/integration/test_authentication.py::test_registration_malformed_header ERROR [  1%]
server/tests/integration/test_authentication.py::test_registration_verification_token_invalid ERROR [  2%]
server/tests/integration/test_authentication.py::test_registration_user_info_error ERROR [  3%]
server/tests/integration/test_authentication.py::test_register_token_valid_missing_info1 ERROR [  3%]
server/tests/integration/test_authentication.py::test_register_token_valid_missing_info2 ERROR [  4%]
server/tests/integration/test_authentication.py::test_registration_user_id_already_exists ERROR [  5%]
server/tests/integration/test_authentication.py::test_successful_user_registration ERROR [  6%]
server/tests/integration/test_leaderboard.py::test_get_leaders_no_completed_puzzle ERROR [  6%]
server/tests/integration/test_leaderboard.py::test_get_leaders_completed_puzzles ERROR [  7%]
server/tests/integration/test_leaderboard.py::test_get_leaders_completed_puzzles_limit2 ERROR [  8%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_use_game_without_registration ERROR [  9%]
server/tests/integration/test_sudoku_endpoints.py::test_get_all_puzzles_no_puzzles ERROR [  9%]
server/tests/integration/test_sudoku_endpoints.py::test_get_nonexistent_puzzle ERROR [ 10%]
server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_valid ERROR [ 11%]
server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_invalid_difficulty_small ERROR [ 12%]
server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_invalid_difficulty_large ERROR [ 12%]
server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_invalid_size_large ERROR [ 13%]
server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_invalid_size_small ERROR [ 14%]
server/tests/integration/test_sudoku_endpoints.py::test_get_all_puzzles_for_user ERROR [ 15%]
server/tests/integration/test_sudoku_endpoints.py::test_get_puzzle_valid ERROR [ 15%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_get_unaffiliated_puzzle ERROR [ 16%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_add_player_to_puzzle_already_in_puzzle ERROR [ 17%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_add_player_to_puzzle_that_doesnt_exist ERROR [ 18%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_add_player_to_puzzle_valid ERROR [ 18%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_join_puzzle_max_players_reached ERROR [ 19%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_valid_no_value_yet ERROR [ 20%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_valid_override_value ERROR [ 21%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_player_is_not_affiliated_with ERROR [ 21%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_invalid_piece_low ERROR [ 22%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_invalid_piece_high ERROR [ 23%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_invalid_position_high ERROR [ 24%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_invalid_position_low ERROR [ 25%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_remove_piece ERROR [ 25%]
server/tests/integration/test_sudoku_endpoints.py::test_attempt_remove_static_piece ERROR [ 26%]
server/tests/integration/test_sudoku_endpoints.py::test_get_puzzle_solution_incomplete ERROR [ 27%]
server/tests/unit/test_authentication.py::test_authorize_token_missing_header PASSED [ 28%]
server/tests/unit/test_authentication.py::test_authorize_token_missing_header2 PASSED [ 28%]
server/tests/unit/test_authentication.py::test_authorize_token_malformed_header PASSED [ 29%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_error PASSED [ 30%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_success_register PASSED [ 31%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_success PASSED [ 31%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_not_registered PASSED [ 32%]
server/tests/unit/test_authentication.py::test_register PASSED           [ 33%]
server/tests/unit/test_authentication.py::test_register_missing_info_email PASSED [ 34%]
server/tests/unit/test_authentication.py::test_register_missing_info_id PASSED [ 34%]
server/tests/unit/test_authentication.py::test_register_error_googleauth PASSED [ 35%]
server/tests/unit/test_authentication.py::test_register_exception PASSED [ 36%]
server/tests/unit/test_authentication.py::test_register_no_user_yet PASSED [ 37%]
server/tests/unit/test_authentication.py::test_register_exception_db PASSED [ 37%]
server/tests/unit/test_google_auth.py::test_validate_token PASSED        [ 38%]
server/tests/unit/test_google_auth.py::test_get_user_information PASSED  [ 39%]
server/tests/unit/test_leaderboard.py::test_get_leaderboard_no_leaders PASSED [ 40%]
server/tests/unit/test_leaderboard.py::test_get_leaderboard PASSED       [ 40%]
server/tests/unit/test_player.py::test_save_commit FAILED                [ 41%]
server/tests/unit/test_player.py::test_save FAILED                       [ 42%]
server/tests/unit/test_player.py::test_find_all_puzzles_for_player PASSED [ 43%]
server/tests/unit/test_player.py::test_find_players_for_puzzle PASSED    [ 43%]
server/tests/unit/test_player.py::test_add_player_to_puzzle_already_too_many_players PASSED [ 44%]
server/tests/unit/test_player.py::test_add_player_to_puzzle_player_doesnt_exist PASSED [ 45%]
server/tests/unit/test_player.py::test_add_player_to_puzzle_ok FAILED    [ 46%]
server/tests/unit/test_player.py::test_to_player_to_str PASSED           [ 46%]
server/tests/unit/test_puzzle_exception.py::test_get_message PASSED      [ 47%]
server/tests/unit/test_puzzle_pieces.py::test_find_all_pieces PASSED     [ 48%]
server/tests/unit/test_puzzle_pieces.py::test_get_piece PASSED           [ 49%]
server/tests/unit/test_puzzle_pieces.py::test_get_piece_none PASSED      [ 50%]
server/tests/unit/test_puzzle_pieces.py::test_save_autocommit PASSED     [ 50%]
server/tests/unit/test_puzzle_pieces.py::test_save PASSED                [ 51%]
server/tests/unit/test_puzzle_pieces.py::test_update_success PASSED      [ 52%]
server/tests/unit/test_puzzle_pieces.py::test_update_fail_static PASSED  [ 53%]
server/tests/unit/test_puzzle_pieces.py::test_get_as_str PASSED          [ 53%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_valid_defaults PASSED [ 54%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_valid_specification PASSED [ 55%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_difficulty_str PASSED [ 56%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_difficulty_too_low PASSED [ 56%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_difficulty_too_high PASSED [ 57%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_size_str PASSED [ 58%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_size_too_low PASSED [ 59%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_size_too_high PASSED [ 59%]
server/tests/unit/test_sudoku_puzzle.py::test_set_point_value1 PASSED    [ 60%]
server/tests/unit/test_sudoku_puzzle.py::test_set_point_value2 PASSED    [ 61%]
server/tests/unit/test_sudoku_puzzle.py::test_get_pieces_as_arr_all PASSED [ 62%]
server/tests/unit/test_sudoku_puzzle.py::test_get_pieces_as_arr_static_only PASSED [ 62%]
server/tests/unit/test_sudoku_puzzle.py::test_recreate_original_puzzle PASSED [ 63%]
server/tests/unit/test_sudoku_puzzle.py::test_check_for_completion_null_values PASSED [ 64%]
server/tests/unit/test_sudoku_puzzle.py::test_check_for_completion_complete PASSED [ 65%]
server/tests/unit/test_sudoku_puzzle.py::test_check_for_completion_incorrect_values PASSED [ 65%]
server/tests/unit/test_sudoku_puzzle.py::test_check_discrepancies_none PASSED [ 66%]
server/tests/unit/test_sudoku_puzzle.py::test_check_discrepancies_many_incorrect PASSED [ 67%]
server/tests/unit/test_sudoku_puzzle.py::test_check_discrepancies_incomplete_puzzle PASSED [ 68%]
server/tests/unit/test_sudoku_puzzle.py::test_get_puzzle_none PASSED     [ 68%]
server/tests/unit/test_sudoku_puzzle.py::test_get_puzzle_found PASSED    [ 69%]
server/tests/unit/test_sudoku_puzzle.py::test_save FAILED                [ 70%]
server/tests/unit/test_sudoku_puzzle.py::test_save_autocommit FAILED     [ 71%]
server/tests/unit/test_sudoku_puzzle.py::test_attempt_update_complete_puzzle PASSED [ 71%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_coordinate1 PASSED [ 72%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_coordinate2 PASSED [ 73%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_coordinate3 PASSED [ 74%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_coordinate4 PASSED [ 75%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_value1 PASSED [ 75%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_value2 PASSED [ 76%]
server/tests/unit/test_sudoku_puzzle.py::test_update_valid FAILED        [ 77%]
server/tests/unit/test_sudoku_puzzle.py::test_update_valid_complete_puzzle FAILED [ 78%]
server/tests/unit/test_sudoku_puzzle.py::test_set_puzzle_complete FAILED [ 78%]
server/tests/unit/test_sudoku_puzzle.py::test_as_str PASSED              [ 79%]
server/tests/unit/test_sudoku_resources.py::test_sudoku_to_json PASSED   [ 80%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_none PASSED [ 81%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_all PASSED [ 81%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_create_one_known_exception PASSED [ 82%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_create_one_unknown_exception PASSED [ 83%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_create_one PASSED [ 84%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzle_none_retrieved PASSED [ 84%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzle_none_associated PASSED [ 85%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzle_found PASSED [ 86%]
server/tests/unit/test_sudoku_resources.py::test_join_sudoku_puzzle_already_joined PASSED [ 87%]
server/tests/unit/test_sudoku_resources.py::test_join_sudoku_puzzle PASSED [ 87%]
server/tests/unit/test_sudoku_resources.py::test_join_sudoku_puzzle_known_exception PASSED [ 88%]
server/tests/unit/test_sudoku_resources.py::test_join_sudoku_puzzle_unknown_exception PASSED [ 89%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_add_move_not_associated PASSED [ 90%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_add_move PASSED [ 90%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_add_move_invalid PASSED [ 91%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_add_move_exception PASSED [ 92%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_delete_piece PASSED [ 93%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_delete_piece_invalid PASSED [ 93%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_get_solution_not_associated PASSED [ 94%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_get_solution_not_associated_2 PASSED [ 95%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_get_solution PASSED [ 96%]
server/tests/unit/test_user.py::test_create_user PASSED                  [ 96%]
server/tests/unit/test_user.py::test_user_as_str PASSED                  [ 97%]
server/tests/unit/test_user.py::test_user_print PASSED                   [ 98%]
server/tests/unit/test_user.py::test_user_save PASSED                    [ 99%]
server/tests/unit/test_user.py::test_find_by_g_id PASSED                 [100%]

==================================== ERRORS ====================================
______________ ERROR at setup of test_registration_missing_header ______________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py, line 47
  def test_registration_missing_header(test_client, init_db):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_info, user_info_error
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py:47
_____________ ERROR at setup of test_registration_malformed_header _____________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py, line 60
  def test_registration_malformed_header(test_client, init_db):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_info, user_info_error
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py:60
________ ERROR at setup of test_registration_verification_token_invalid ________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py, line 74
  def test_registration_verification_token_invalid(test_client, init_db, verification_error):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_info, user_info_error
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py:74
_____________ ERROR at setup of test_registration_user_info_error ______________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py, line 84
  def test_registration_user_info_error(test_client, init_db, verification_true, user_info_error):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_info, user_info_error
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py:84
__________ ERROR at setup of test_register_token_valid_missing_info1 ___________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py, line 96
  def test_register_token_valid_missing_info1(monkeypatch, test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_info, user_info_error
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py:96
__________ ERROR at setup of test_register_token_valid_missing_info2 ___________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py, line 123
  def test_register_token_valid_missing_info2(monkeypatch, test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_info, user_info_error
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py:123
__________ ERROR at setup of test_registration_user_id_already_exists __________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py, line 150
  def test_registration_user_id_already_exists(monkeypatch, test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_info, user_info_error
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py:150
_____________ ERROR at setup of test_successful_user_registration ______________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py, line 167
  def test_successful_user_registration(test_client, init_db, verification_true, user_info):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_info, user_info_error
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_authentication.py:167
____________ ERROR at setup of test_get_leaders_no_completed_puzzle ____________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_leaderboard.py, line 8
  def test_get_leaders_no_completed_puzzle(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_leaderboard.py:8
_____________ ERROR at setup of test_get_leaders_completed_puzzles _____________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_leaderboard.py, line 18
  def test_get_leaders_completed_puzzles(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_leaderboard.py:18
_________ ERROR at setup of test_get_leaders_completed_puzzles_limit2 __________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_leaderboard.py, line 41
  def test_get_leaders_completed_puzzles_limit2(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_leaderboard.py:41
_______ ERROR at setup of test_attempt_to_use_game_without_registration ________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 10
  def test_attempt_to_use_game_without_registration(monkeypatch, test_client, init_db):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:10
______________ ERROR at setup of test_get_all_puzzles_no_puzzles _______________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 34
  def test_get_all_puzzles_no_puzzles(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:34
________________ ERROR at setup of test_get_nonexistent_puzzle _________________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 46
  def test_get_nonexistent_puzzle(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:46
_________________ ERROR at setup of test_save_new_puzzle_valid _________________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 56
  def test_save_new_puzzle_valid(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:56
_______ ERROR at setup of test_save_new_puzzle_invalid_difficulty_small ________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 72
  def test_save_new_puzzle_invalid_difficulty_small(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:72
_______ ERROR at setup of test_save_new_puzzle_invalid_difficulty_large ________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 87
  def test_save_new_puzzle_invalid_difficulty_large(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:87
__________ ERROR at setup of test_save_new_puzzle_invalid_size_large ___________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 102
  def test_save_new_puzzle_invalid_size_large(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:102
__________ ERROR at setup of test_save_new_puzzle_invalid_size_small ___________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 117
  def test_save_new_puzzle_invalid_size_small(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:117
_______________ ERROR at setup of test_get_all_puzzles_for_user ________________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 132
  def test_get_all_puzzles_for_user(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:132
___________________ ERROR at setup of test_get_puzzle_valid ____________________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 163
  def test_get_puzzle_valid(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:163
__________ ERROR at setup of test_attempt_to_get_unaffiliated_puzzle ___________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 187
  def test_attempt_to_get_unaffiliated_puzzle(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:187
___ ERROR at setup of test_attempt_to_add_player_to_puzzle_already_in_puzzle ___
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 198
  def test_attempt_to_add_player_to_puzzle_already_in_puzzle(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:198
___ ERROR at setup of test_attempt_to_add_player_to_puzzle_that_doesnt_exist ___
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 209
  def test_attempt_to_add_player_to_puzzle_that_doesnt_exist(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:209
_________ ERROR at setup of test_attempt_to_add_player_to_puzzle_valid _________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 221
  def test_attempt_to_add_player_to_puzzle_valid(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:221
______ ERROR at setup of test_attempt_to_join_puzzle_max_players_reached _______
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 232
  def test_attempt_to_join_puzzle_max_players_reached(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:232
_________ ERROR at setup of test_attempt_add_piece_valid_no_value_yet __________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 250
  def test_attempt_add_piece_valid_no_value_yet(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:250
________ ERROR at setup of test_attempt_add_piece_valid_override_value _________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 277
  def test_attempt_add_piece_valid_override_value(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:277
____ ERROR at setup of test_attempt_add_piece_player_is_not_affiliated_with ____
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 305
  def test_attempt_add_piece_player_is_not_affiliated_with(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:305
__________ ERROR at setup of test_attempt_add_piece_invalid_piece_low __________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 323
  def test_attempt_add_piece_invalid_piece_low(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:323
_________ ERROR at setup of test_attempt_add_piece_invalid_piece_high __________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 348
  def test_attempt_add_piece_invalid_piece_high(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:348
________ ERROR at setup of test_attempt_add_piece_invalid_position_high ________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 373
  def test_attempt_add_piece_invalid_position_high(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:373
________ ERROR at setup of test_attempt_add_piece_invalid_position_low _________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 394
  def test_attempt_add_piece_invalid_position_low(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:394
_________________ ERROR at setup of test_attempt_remove_piece __________________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 415
  def test_attempt_remove_piece(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:415
______________ ERROR at setup of test_attempt_remove_static_piece ______________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 442
  def test_attempt_remove_static_piece(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:442
____________ ERROR at setup of test_get_puzzle_solution_incomplete _____________
file /Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py, line 470
  def test_get_puzzle_solution_incomplete(test_client, init_db, verification_true):
E       fixture 'test_client' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/meganfrenkel/Workspace/KERMit/server/tests/integration/test_sudoku_endpoints.py:470
=================================== FAILURES ===================================
_______________________________ test_save_commit _______________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f7fabd4a2e0>

    def test_save_commit(monkeypatch):
        """
        This test is mostly mocks; tests ensure the relevant classes/method are understood.
        """
>       monkeypatch.setattr(db, "session", MockSession)
E       NameError: name 'db' is not defined

server/tests/unit/test_player.py:56: NameError
__________________________________ test_save ___________________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f7fabd94ee0>

    def test_save(monkeypatch):
        """
        This test is mostly mocks; tests ensure the relevant classes/method are understood.
        """
>       monkeypatch.setattr(db, "session", MockSession)
E       NameError: name 'db' is not defined

server/tests/unit/test_player.py:66: NameError
_________________________ test_add_player_to_puzzle_ok _________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f7fabe457f0>

    def test_add_player_to_puzzle_ok(monkeypatch):
        """
        A valid attempt to add a player to a puzzle should be successful.
        """
        def mock_return_existing_players(*args, **kwargs):
            """
            Mock return existing players for the request.
            """
            user1 = User('923423', first_name="Tester1",
                         last_name="Tester1", email='test1@tests.com')
            user2 = User('12345', first_name="Tester2",
                         last_name="Tester2", email='tes2t@tests.com')
            return [user1, user2]
    
>       monkeypatch.setattr(db, "session", MockSession)
E       NameError: name 'db' is not defined

server/tests/unit/test_player.py:147: NameError
__________________________________ test_save ___________________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f7fabea2e80>
complete_puzzle = <Puzzle (transient 140186321825744)>

    def test_save(monkeypatch, complete_puzzle):
        """
        Test save a puzzle, mocking the database session action and with autocommit off.
        """
>       monkeypatch.setattr(db, "session", MockSession)
E       NameError: name 'db' is not defined

server/tests/unit/test_sudoku_puzzle.py:375: NameError
_____________________________ test_save_autocommit _____________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f7fac075a90>
complete_puzzle = <Puzzle (transient 140186323737328)>

    def test_save_autocommit(monkeypatch, complete_puzzle):
        """
        Test save a puzzle, mocking the database session action and with autocommit on.
        """
>       monkeypatch.setattr(db, "session", MockSession)
E       NameError: name 'db' is not defined

server/tests/unit/test_sudoku_puzzle.py:385: NameError
______________________________ test_update_valid _______________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f7fabe5f550>
incomplete_puzzle = <Puzzle (transient 140186321550496)>

    def test_update_valid(monkeypatch, incomplete_puzzle):
        """
        If user supplies valid piece to valid coordinates on puzzle, update should be successful.
        """
>       monkeypatch.setattr(db, "session", MockSession)
E       NameError: name 'db' is not defined

server/tests/unit/test_sudoku_puzzle.py:463: NameError
______________________ test_update_valid_complete_puzzle _______________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f7fabe608e0>
incomplete_puzzle = <Puzzle (transient 140186321554352)>

    def test_update_valid_complete_puzzle(monkeypatch, incomplete_puzzle):
        """
        Adding the last piece to the puzzle should result in the puzzle being marked as completed.
        """
>       monkeypatch.setattr(db, "session", MockSession)
E       NameError: name 'db' is not defined

server/tests/unit/test_sudoku_puzzle.py:475: NameError
___________________________ test_set_puzzle_complete ___________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f7fabea2dc0>
incomplete_puzzle = <Puzzle (transient 140186321822240)>

    def test_set_puzzle_complete(monkeypatch, incomplete_puzzle):
        """
        Calling the set_puzzle_complete() method should mark the puzzle as completed.
        """
>       monkeypatch.setattr(db, "session", MockSession)
E       NameError: name 'db' is not defined

server/tests/unit/test_sudoku_puzzle.py:492: NameError
=============================== warnings summary ===============================
server/venv/lib/python3.8/site-packages/eventlet/patcher.py:1
  /Users/meganfrenkel/Workspace/KERMit/server/venv/lib/python3.8/site-packages/eventlet/patcher.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

server/venv/lib/python3.8/site-packages/dns/hash.py:23
  /Users/meganfrenkel/Workspace/KERMit/server/venv/lib/python3.8/site-packages/dns/hash.py:23: DeprecationWarning: dns.hash module will be removed in future versions. Please use hashlib instead.
    warnings.warn(

server/venv/lib/python3.8/site-packages/dns/namedict.py:35
  /Users/meganfrenkel/Workspace/KERMit/server/venv/lib/python3.8/site-packages/dns/namedict.py:35: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    class NameDict(collections.MutableMapping):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED server/tests/unit/test_player.py::test_save_commit - NameError: name '...
FAILED server/tests/unit/test_player.py::test_save - NameError: name 'db' is ...
FAILED server/tests/unit/test_player.py::test_add_player_to_puzzle_ok - NameE...
FAILED server/tests/unit/test_sudoku_puzzle.py::test_save - NameError: name '...
FAILED server/tests/unit/test_sudoku_puzzle.py::test_save_autocommit - NameEr...
FAILED server/tests/unit/test_sudoku_puzzle.py::test_update_valid - NameError...
FAILED server/tests/unit/test_sudoku_puzzle.py::test_update_valid_complete_puzzle
FAILED server/tests/unit/test_sudoku_puzzle.py::test_set_puzzle_complete - Na...
ERROR server/tests/integration/test_authentication.py::test_registration_missing_header
ERROR server/tests/integration/test_authentication.py::test_registration_malformed_header
ERROR server/tests/integration/test_authentication.py::test_registration_verification_token_invalid
ERROR server/tests/integration/test_authentication.py::test_registration_user_info_error
ERROR server/tests/integration/test_authentication.py::test_register_token_valid_missing_info1
ERROR server/tests/integration/test_authentication.py::test_register_token_valid_missing_info2
ERROR server/tests/integration/test_authentication.py::test_registration_user_id_already_exists
ERROR server/tests/integration/test_authentication.py::test_successful_user_registration
ERROR server/tests/integration/test_leaderboard.py::test_get_leaders_no_completed_puzzle
ERROR server/tests/integration/test_leaderboard.py::test_get_leaders_completed_puzzles
ERROR server/tests/integration/test_leaderboard.py::test_get_leaders_completed_puzzles_limit2
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_use_game_without_registration
ERROR server/tests/integration/test_sudoku_endpoints.py::test_get_all_puzzles_no_puzzles
ERROR server/tests/integration/test_sudoku_endpoints.py::test_get_nonexistent_puzzle
ERROR server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_valid
ERROR server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_invalid_difficulty_small
ERROR server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_invalid_difficulty_large
ERROR server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_invalid_size_large
ERROR server/tests/integration/test_sudoku_endpoints.py::test_save_new_puzzle_invalid_size_small
ERROR server/tests/integration/test_sudoku_endpoints.py::test_get_all_puzzles_for_user
ERROR server/tests/integration/test_sudoku_endpoints.py::test_get_puzzle_valid
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_get_unaffiliated_puzzle
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_add_player_to_puzzle_already_in_puzzle
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_add_player_to_puzzle_that_doesnt_exist
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_add_player_to_puzzle_valid
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_to_join_puzzle_max_players_reached
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_valid_no_value_yet
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_valid_override_value
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_player_is_not_affiliated_with
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_invalid_piece_low
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_invalid_piece_high
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_invalid_position_high
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_add_piece_invalid_position_low
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_remove_piece
ERROR server/tests/integration/test_sudoku_endpoints.py::test_attempt_remove_static_piece
ERROR server/tests/integration/test_sudoku_endpoints.py::test_get_puzzle_solution_incomplete
============= 8 failed, 88 passed, 3 warnings, 36 errors in 1.91s ==============
